# .github/workflows/publish.yml
name: Publish to npm

on:
  push:
    tags:
      - "v*" # Trigger when a tag like v1.0.0 is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          always-auth: true
          scope: "@jabirdev"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
