name: Publish to npm
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build, bump & publish to npm
    runs-on: ubuntu-latest
    container: httptoolkit/act-build-base:v3.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Clean cache
        run: npm cache clean --force

      - name: Remove node_modules
        run: rm -rf node_modules

      - run: npm i --force

      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Build package
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish
